#!/usr/bin/env python3
"""
Navbar Template Module
Provides a consistent navbar script tag for all pages
"""


def get_navbar_html(level="root"):
    """
    Generate navbar script tag with appropriate relative paths
    
    Args:
        level (str): The directory level - "root", "directory", or "subdirectory"
                    - "root": for index.html (at repository root)
                    - "directory": for files in index.directory/
                    - "subdirectory": for files in index.directory/trades/ etc.
    
    Returns:
        str: Comment indicating navbar is generated by navbar.js
    """
    
    # The navbar is now generated dynamically by navbar.js
    # No need to generate HTML, just return a comment
    return """  <!-- Navigation - Generated by navbar.js -->"""
