# GitHub Pages Configuration for SFTi-Pennies Trading Journal
# Root configuration to ensure proper site building

# Site settings
title: "SFTi-Pennies Trading Journal"
description: "Professional penny stock trading journal with automated tracking and analysis"
baseurl: ""
url: "https://statikfintechllc.github.io/SFTi-Pennies"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing - files with colons cause Jekyll build errors
# Note: We keep SFTi.Tradez markdown files accessible for modal loading
exclude:
  - README.md
  - TODO.Feat.md
  - DIRECTORY_STRUCTURE.md
  - FIXES_SUMMARY.md
  - .github/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - package.json
  - package-lock.json
  - LICENSE.md
  - index.directory/src/

# Include necessary files - force Jekyll to include assets even with colons in path
include:
  - index.directory/_config.yml

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: false
