blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/statikfintechllc/SFTi-Pennies/tree/main/.github/docs
    about: Check comprehensive documentation including README-DEV.md, QUICKSTART.md, and more
  - name: 💬 Discussions
    url: https://github.com/statikfintechllc/SFTi-Pennies/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/statikfintechllc/SFTi-Pennies/security/advisories/new
    about: Report security vulnerabilities privately
