name: Nightly Analytics

# Run analytics generation nightly at 2 AM UTC
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-analytics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml matplotlib
      
      - name: Re-parse trades
        run: |
          echo "Re-parsing trades from markdown files..."
          python .github/scripts/parse_trades.py
      
      - name: Generate analytics
        run: |
          echo "Generating advanced analytics..."
          python .github/scripts/generate_analytics.py
      
      - name: Generate summaries
        run: |
          echo "Generating summaries..."
          python .github/scripts/generate_summaries.py
      
      - name: Generate charts
        run: |
          echo "Generating charts..."
          python .github/scripts/generate_charts.py
      
      - name: Update homepage
        run: |
          echo "Updating homepage..."
          python .github/scripts/update_homepage.py
      
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Commit changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: Nightly analytics regeneration [skip ci]"
            git push
          fi
